### ISSUE TITLE
queryRecursiveConfirm message missing p2ps structure.

### ISSUE THREAD

**Issue by jmacauley** [BandwidthOnDemand/nsi-safnari#18]
nsi-safnari is not populating the p2ps structure associated with its service entry in the criteria element of the queryRecursiveConfirmed.  The following message returned from nsi-safnari shows the issue:

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:headers="http://schemas.ogf.org/nsi/2013/12/framework/headers" 
        xmlns:p2p="http://schemas.ogf.org/nsi/2013/12/services/point2point" 
        xmlns:nsi="http://schemas.ogf.org/nsi/2013/12/connection/types"
        xmlns:types="http://schemas.ogf.org/nsi/2013/12/services/types"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        http://schemas.xmlsoap.org/soap/envelope/ file:../envelope.xsd
        http://schemas.ogf.org/nsi/2013/12/connection/types file:../ogf_nsi_connection_types_v2_0.xsd
        http://schemas.ogf.org/nsi/2013/12/services/types file:../ogf_nsi_services_types_v2_0.xsd
        http://schemas.ogf.org/nsi/2013/12/services/point2point file:../ogf_nsi_services_p2p_v2_0.xsd
        http://schemas.ogf.org/nsi/2013/12/framework/types file:../ogf_nsi_framework_types_v2_0.xsd">
        <soapenv:Header>
            <headers:nsiHeader>
                <protocolVersion>application/vnd.ogf.nsi.cs.v2.requester+soap</protocolVersion>
                <correlationId>urn:uuid:4f568d07-7ecb-11e7-8397-0c4de99a207f</correlationId>
                <requesterNSA>urn:ogf:network:canada.eh:2016:nsa:requester</requesterNSA>
                <providerNSA>urn:ogf:network:es.net:2013:nsa:nsi-aggr-west</providerNSA>
            </headers:nsiHeader>
        </soapenv:Header>
        <soapenv:Body>
            <nsi:queryRecursiveConfirmed>
                <reservation>
                    <connectionId>2da2f26f-d931-4a35-b9ca-084a750d0b5f</connectionId>
                    <criteria version="0">
                        <schedule>
                            <startTime>2017-08-11T19:21:00Z</startTime>
                            <endTime>2017-08-11T19:26:00Z</endTime>
                        </schedule>
                        <serviceType>http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE</serviceType>
                        <children>
                            <child order="0">
                                <connectionId>IC-7b95391b8e</connectionId>
                                <providerNSA>urn:ogf:network:icair.org:2013:nsa</providerNSA>
                                <connectionStates>
                                    <reservationState>ReserveStart</reservationState>
                                    <provisionState>Provisioned</provisionState>
                                    <lifecycleState>Created</lifecycleState>
                                    <dataPlaneStatus>
                                        <active>false</active>
                                        <version>0</version>
                                        <versionConsistent>true</versionConsistent>
                                    </dataPlaneStatus>
                                </connectionStates>
                                <criteria version="0">
                                    <schedule>
                                        <startTime>2017-08-11T19:21:00Z</startTime>
                                        <endTime>2017-08-11T19:26:00Z</endTime>
                                    </schedule>
                                    <serviceType>{http://schemas.ogf.org/nsi/2013/12/services/point2point}p2ps</serviceType>
                                    <children>
                                        <child order="0">
                                            <connectionId>IC-7b95391b8e</connectionId>
                                            <providerNSA>urn:ogf:network:icair.org:2013:nsa</providerNSA>
                                            <connectionStates>
                                                <reservationState>ReserveStart</reservationState>
                                                <provisionState>Provisioned</provisionState>
                                                <lifecycleState>PassedEndTime</lifecycleState>
                                                <dataPlaneStatus>
                                                    <active>false</active>
                                                    <version>0</version>
                                                    <versionConsistent>true</versionConsistent>
                                                </dataPlaneStatus>
                                            </connectionStates>
                                            <criteria version="0">
                                                <schedule>
                                                    <startTime>2017-08-11T19:21:00Z</startTime>
                                                    <endTime>2017-08-11T19:26:00Z</endTime>
                                                </schedule>
                                                <serviceType>{http://schemas.ogf.org/nsi/2013/12/services/point2point}p2ps</serviceType>
                                                <children/>
                                                <p2p:p2ps>
                                                    <capacity>100</capacity>
                                                    <directionality>Bidirectional</directionality>
                                                    <symmetricPath>false</symmetricPath>
                                                    <sourceSTP>urn:ogf:network:icair.org:2013:topology:pwave-pnwgp_chcg?vlan=1779</sourceSTP>
                                                    <destSTP>urn:ogf:network:icair.org:2013:topology:ps?vlan=1779</destSTP>
                                                </p2p:p2ps>
                                            </criteria>
                                        </child>
                                    </children>
                                    <p2p:p2ps>
                                        <capacity>100</capacity>
                                        <directionality>Bidirectional</directionality>
                                        <symmetricPath>false</symmetricPath>
                                        <sourceSTP>urn:ogf:network:icair.org:2013:topology:pwave-pnwgp_chcg?vlan=1779</sourceSTP>
                                        <destSTP>urn:ogf:network:icair.org:2013:topology:ps?vlan=1779</destSTP>
                                    </p2p:p2ps>
                                </criteria>
                            </child>
                        </children>
                        
                    </criteria>
                    <requesterNSA>urn:ogf:network:canada.eh:2016:nsa:requester</requesterNSA>
                    <connectionStates>
                        <reservationState>ReserveStart</reservationState>
                        <provisionState>Provisioned</provisionState>
                        <lifecycleState>PassedEndTime</lifecycleState>
                        <dataPlaneStatus>
                            <active>false</active>
                            <version>0</version>
                            <versionConsistent>true</versionConsistent>
                        </dataPlaneStatus>
                    </connectionStates>
                </reservation>
            </nsi:queryRecursiveConfirmed>
        </soapenv:Body>
    </soapenv:Envelope>

**Comment by erikrozendaal** [comment]
Merged your fix. Thanks!
